name: Process changes

on:
  schedule:
    - cron: "30 5 * * *"

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          path: ./data
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          path: ./code
          repository: colonial-heritage/integration
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install and build packages
        run: |
          cd ./code
          npm ci
          npm run build
      - name: Fetch IRIs of changed resources
        run: |
          cd ./data
          ../code/packages/iiif-change-storer/dist/cli.js fetch \
            --collection-iri "https://iiif.bodleian.ox.ac.uk/iiif/activity/all-changes" \
            --dir-with-runs "./runs" \
            --file-with-metadata "./metadata.csv" \
            --wait-between-requests 0
      - name: Process changed resources
        run: |
          cd ./data
          ../code/packages/iiif-change-storer/dist/cli.js process \
            --file-with-metadata "./metadata.csv" \
            --dir-with-files-with-metadata "$RUNNER_TEMP/chunks" \
            --number-of-lines-per-file-with-metadata 5000 \
            --dir-with-changes "./resources" \
            --wait-between-requests 0 \
            --number-of-concurrent-requests 25
      - name: Save changes to repository
        run: |
          cd ./data
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --quiet -a -m "Save changes" || true
          git push --force -u origin
